version: '3.8'
services:
  airflow-webserver:
    image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.8.1}
    restart: always
    network_mode: bridge
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=''
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__LOGGING_LEVEL=INFO
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - GCP_GCS_BUCKET=${GCP_GCS_BUCKET}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./data_loader/dags:/opt/airflow/dags
      - ./data_loader/logs:/opt/airflow/logs
      - ./data_loader/plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./google_credentials.json:/opt/airflow/google_credentials.json # Mapping your GCP key
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.8.1}
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./data_loader/dags:/opt/airflow/dags
      - ./data_loader/logs:/opt/airflow/logs
      - ./google_credentials.json:/opt/airflow/google_credentials.json
    command: scheduler

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"