user:
  outputs:
    default:
      keyfile_json:
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        auth_uri: https://accounts.google.com/o/oauth2/auth
        client_email: terraform-runner@dataengineeringtutorial.iam.gserviceaccount.com
        client_id: '103416820384491496896'
        client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/terraform-runner%40dataengineeringtutorial.iam.gserviceaccount.com
        private_key: '-----BEGIN PRIVATE KEY-----

          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCtB3tj2dFgheU+

          llQu7zOEubrq/wh16mXYuLDTcpx6EBzqGsqBs24yZeAJUHq7rZEGL1XEhl0+QAj0

          vh3jaR+VdEsAZW1fsbfIIydydtIKhIf4mdB6K0ZwhOHXi3seXZS2PChJI9oC5Hcw

          8t+7Hj+MFgL9SN0uawWBKVejfP7Vbojyl5/0aWnSgltzujw1m0dcR+7Kz0X5/v21

          OHukpoWM+xYn0JeFlrblpq/Sbjq5D20K3OxsB0uUSzDC3rhonTTg1YNVAe9bBxLH

          i1w0DoBc7x03VnePfxq95LRoXxNflkjqv2MDmBsDv+XqFFn3PIv5O3MHO/7YJRRp

          NnBo2N3zAgMBAAECggEACAvChZyh21quk8/6vyn5W9ElK3tLgewx6zd/ZX29YAGy

          zoILa6eT1r0dA2HeKy8BgOefleFnoZbps7PJgQMo6FK9kBmnUd1aPfDAi1aSItIR

          3pIMezna7y2GsPa39WwFl8nJV8lWgG7uSfTpSXK5IsL9RZjnTBrG6UAqZpxP303O

          Yg+B+YuZWixRkqvC3zc/lIbEUPVS17sD7tHO9s3t39lW6iEYyPBqC7yYXldkQvxE

          2hwF9/pdtPX9X2CLFBaPunFxbsziQTbqao96TtqXaXj6VyLcrhxSo4nkgGZndleg

          /fsuSqNi/0KCDoz4eAklMJi+/oWTmkTYeGeuTSxB3QKBgQDmZUpXcXKQhZMtJ7sZ

          wPTp2UMA0aTk988JDvPEfuApTF5EY0r02gLjNwaiil0uD8n8Pgkb6+92firnb243

          tCJ6/3uuimbtgT7aj3Jl7wGneqsUtdgI5/t6uvBYr/0j1I31oHxeO9BWNGYHGDPd

          z0+1qyg3p64MmyNgowEns8Z3vQKBgQDAQiDM8DROS1LqAMkd6+HmE/rSBfbcEZ0l

          bWC/qhbHSoyK6dxKwf1WFaS0iZE61NMKtE8VLEWOfweae/pl2ttt5h/r3zOi9fNt

          pbBOETqFzJom/Uw2teDjxZZlsSqMEACG5p6PMOU+GTCDoRxV7xZbmQ2uGWfh3uKk

          lzITFWBvbwKBgQCf0YGJOMwEznOybg4Oplf941TkO4jLv86g9PtJwc0TOMNnYw06

          3gQEw0XZ+Gr8qb0uOYYuFTLOGmT+l8B36X/FnHWaNK2DcRU9nSX46ZtXJvOH8UBD

          pVA/6W8Rxjqt4SL8UPAUmh9BvSVNJI/N/KHJXkoOmUVVv0QCI/CILt+sbQKBgGY+

          hL0YfWip7EVf95T/DhrSw1AQNfFhOKZf3dTwOr7vqYBy0GG9euHeDsKoamDUMAwA

          ShJjgfY/HicNCeRDGPEAMje5cveWP0gvlmxeAzaG0fAsQuzRmvDm8o3QQ2VLWUxk

          tyxFf5Sfxsop0yzsQoKiCcFt524an4OSmOHHO4rnAoGAU7uDWKfFwWkDWOo5n3sD

          KjYXL67WGiUdV9hIKG/CN1EHSy4qmCEqD3ICPqL36aC59FcVAlC1qJcb3UWxgic3

          utr6uQcwDSOUtnq9jl8EKpoEO3TwVfdJ15mFmPcQXHDt7hQ90vBV88ymQi6biu9C

          ivQjYJBrTvJUbnluXEQI9M4=

          -----END PRIVATE KEY-----

          '
        private_key_id: 06cb448e3bca5caa3c25435e667693a46e7bc7f6
        project_id: santander-bikes-pipeline
        token_uri: https://oauth2.googleapis.com/token
        type: service_account
      location: europe-west2
      method: service-account-json
      project: santander-bikes-pipeline
      schema: dbt_wmohamed
      scopes:
      - https://www.googleapis.com/auth/bigquery
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/drive
      - https://www.googleapis.com/auth/userinfo.email
      target_name: default
      threads: 6
      type: bigquery
  target: default
